### ISSUE TITLE
Checklist for new version release - TEMPLATE

### ISSUE THREAD

**Issue by verku** [NBISweden/DNAharvester#82]
- [ ]  Feature branches merged into dev
- [ ]  Test runs finished successfully (github and on cluster)
- [ ]  Changelog updated
- [ ]  Version number updated
- [ ]  If needed, pipeline documentation updated and all branches merged into documentation main
- [ ]  dev merged into main
- [ ]  New tag and version release
- [ ]  Issues closed
