### ISSUE TITLE
Checklist for version 0.1.0 release (January 21st)

### ISSUE THREAD

**Issue by verku** [NBISweden/DNAharvester#83]
- [x]  Feature branches merged into dev
- [x]  Test runs finished successfully (test dataset on cluster)
- [x]  Changelog created
- [x]  Version number updated
- [x]  Pipeline documentation branches merged into documentation main
- [x]  dev merged into main
- [x]  New tag and version release
- [x]  Issues closed

See checklist below for more details!

**Comment by verku** [comment]
We will arrange a meeting on 16 January 10.30-12 (using the methods meeting) to introduce the pipeline. The code will be made available from 20 January.

To do before 16 January:

- [x] Update pipeline map as needed (@verku )
- [x] Update documentation (@verku )
- [x] Agree on pipeline name (everyone)
- [x] Create a slack channel for pipeline users (@bilalbioinfo )
- [x] Prepare for meeting on 16th: create an example dataset, prepare a sample sheet, config file, compute config (@bilalbioinfo )

To do before 20 January:

- [x] Merge dev-bilal into dev (@bilalbioinfo )
- [x] Run tiny testdata on dev (@verku , @bilalbioinfo )
- [x] Run genome-wide testdata on dev (@bilalbioinfo )
- [x] For any new bug fixes and changes, create new branches for merging into dev (@verku , @bilalbioinfo )
- [x] Rename the repository on 17th (@verku )
- [x] Add version number 0.1.0 for the internal release

> In the future, a new version with changes that are still compatible with the previous version will increase the third number (i.e. 0.1.0 → 0.1.1). A new version with changes that are incompatible with the previous version will increase the second number (i.e. 0.1.X → 0.2.0)

- [x] Make sure the documentation and pipeline map is up to date after the meeting on 16th (@verku )
- [x] Make sure all configs are identical (`custom.config`, `nextflow.config`, github actions config files)
- [x] Merge dev into main on 21st (@bilalbioinfo , @verku )
- [x] Tag the repository and create a version release (@bilalbioinfo , @verku )

**Comment by verku** [comment]
- [x] Guidelines on how to clone repository (private) & SSH keys - slack channel
- [x] Doublecheck documentation
- [x] Look into license
